# Generated by Django 5.2.6 on 2025-09-20 16:00

from django.db import migrations


def create_initial_data(apps, schema_editor):
    product = apps.get_model("orders", "Product")
    order = apps.get_model("orders", "Order")

    # Crea prodotti
    p1 = product.objects.create(name="Prodotto 1", price=10)
    p2 = product.objects.create(name="Prodotto 2", price=20)
    p3 = product.objects.create(name="Prodotto 3", price=30)

    # Crea ordini
    o1 = order.objects.create(name="Ordine A", description="Un prodotto")
    o2 = order.objects.create(name="Ordine B", description="Due prodotti")
    o3 = order.objects.create(name="Ordine C", description="Tre prodotti")

    # Collega prodotti agli ordini
    o1.products.add(p1)
    o2.products.add(p1, p2)
    o3.products.add(p1, p2, p3)


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_initial_data)]
